/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DnsRouteImport } from './routes/dns'
import { Route as PlikiRouteImport } from './routes/pliki'
import { Route as PomiarRouteImport } from './routes/pomiar'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as ApiSpeedDownRouteImport } from './routes/api/speed/down'
import { Route as ApiSpeedPingRouteImport } from './routes/api/speed/ping'
import { Route as ApiSpeedUpRouteImport } from './routes/api/speed/up'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsRoute = DnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const PlikiRoute = PlikiRouteImport.update({
  id: '/pliki',
  path: '/pliki',
  getParentRoute: () => rootRouteImport,
} as any)
const PomiarRoute = PomiarRouteImport.update({
  id: '/pomiar',
  path: '/pomiar',
  getParentRoute: () => rootRouteImport,
} as any)
const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeedDownRoute = ApiSpeedDownRouteImport.update({
  id: '/api/speed/down',
  path: '/api/speed/down',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeedPingRoute = ApiSpeedPingRouteImport.update({
  id: '/api/speed/ping',
  path: '/api/speed/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeedUpRoute = ApiSpeedUpRouteImport.update({
  id: '/api/speed/up',
  path: '/api/speed/up',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dns': typeof DnsRoute
  '/pliki': typeof PlikiRoute
  '/pomiar': typeof PomiarRoute
  '/tuner': typeof TunerRoute
  '/api/speed/down': typeof ApiSpeedDownRoute
  '/api/speed/ping': typeof ApiSpeedPingRoute
  '/api/speed/up': typeof ApiSpeedUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dns': typeof DnsRoute
  '/pliki': typeof PlikiRoute
  '/pomiar': typeof PomiarRoute
  '/tuner': typeof TunerRoute
  '/api/speed/down': typeof ApiSpeedDownRoute
  '/api/speed/ping': typeof ApiSpeedPingRoute
  '/api/speed/up': typeof ApiSpeedUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dns': typeof DnsRoute
  '/pliki': typeof PlikiRoute
  '/pomiar': typeof PomiarRoute
  '/tuner': typeof TunerRoute
  '/api/speed/down': typeof ApiSpeedDownRoute
  '/api/speed/ping': typeof ApiSpeedPingRoute
  '/api/speed/up': typeof ApiSpeedUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dns'
    | '/pliki'
    | '/pomiar'
    | '/tuner'
    | '/api/speed/down'
    | '/api/speed/ping'
    | '/api/speed/up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dns'
    | '/pliki'
    | '/pomiar'
    | '/tuner'
    | '/api/speed/down'
    | '/api/speed/ping'
    | '/api/speed/up'
  id:
    | '__root__'
    | '/'
    | '/dns'
    | '/pliki'
    | '/pomiar'
    | '/tuner'
    | '/api/speed/down'
    | '/api/speed/ping'
    | '/api/speed/up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DnsRoute: typeof DnsRoute
  PlikiRoute: typeof PlikiRoute
  PomiarRoute: typeof PomiarRoute
  TunerRoute: typeof TunerRoute
  ApiSpeedDownRoute: typeof ApiSpeedDownRoute
  ApiSpeedPingRoute: typeof ApiSpeedPingRoute
  ApiSpeedUpRoute: typeof ApiSpeedUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns': {
      id: '/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pliki': {
      id: '/pliki'
      path: '/pliki'
      fullPath: '/pliki'
      preLoaderRoute: typeof PlikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomiar': {
      id: '/pomiar'
      path: '/pomiar'
      fullPath: '/pomiar'
      preLoaderRoute: typeof PomiarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speed/down': {
      id: '/api/speed/down'
      path: '/api/speed/down'
      fullPath: '/api/speed/down'
      preLoaderRoute: typeof ApiSpeedDownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speed/ping': {
      id: '/api/speed/ping'
      path: '/api/speed/ping'
      fullPath: '/api/speed/ping'
      preLoaderRoute: typeof ApiSpeedPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speed/up': {
      id: '/api/speed/up'
      path: '/api/speed/up'
      fullPath: '/api/speed/up'
      preLoaderRoute: typeof ApiSpeedUpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DnsRoute: DnsRoute,
  PlikiRoute: PlikiRoute,
  PomiarRoute: PomiarRoute,
  TunerRoute: TunerRoute,
  ApiSpeedDownRoute: ApiSpeedDownRoute,
  ApiSpeedPingRoute: ApiSpeedPingRoute,
  ApiSpeedUpRoute: ApiSpeedUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
